name: ContestController
main: ru.craftcoderr.contestcontroller.ContestControllerPlugin
api-version: "1.17"
version: "0.1"
description: "Contest plots controller"
authors: [CraftCoderr]
depend: [PlotSquared, PlotHider, LuckPerms]
